config/routes.rb
Rails.application.routes.draw do
  root 'news#home'
  
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  resources :users, only: [:new, :create]
  
  resources :news, except: :index do
    resources:comments, only: [:create, :destroy]
  end
  
  get '/comments' => 'comments#index'
  
  get '/submit' => 'news#submit'
  
  get '/home' => 'news#home'
  
  get '/submit' => 'news#test'
  

  get 'about/about'
  

  
  

end

app/models/comments.rb
class Comment < ActiveRecord::Base
    validates :message,
        presence: true,
        length: {minimum: 8, maximum: 1000},
        allow_blank: false
end
       

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/submit.rb
class Submit < ActiveRecord::Base
    validates :text,
        presence: true,
        length: {minimum: 10, maximum: 200}
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    
    validates :username,
                presence: true,
                length: { minimum: 10, maximum: 15 },
                format: { with: /[a-zA-Z0-9_@-]/},
                uniqueness: { case_sensitive: false }
    
    validates :email,
                presence: true
    
    validates :password, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout "application"
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def login(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logout
    session.delete(:user_id)
    @current_user = nil
  end

  def logged_in?
    current_user.nil? ? false : true
  end
  
  helper_method :current_user, :logged_in?
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def index
    end
    
    def create
    end
    
    def destroy
    end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
    def index
        @newsall = News.all
    end
  
   # def new
   #     @newsstory = NewsStory.new
   # end
  
   # def create
    #    @newsstory = NewsStory.new(params[:newsstory ])
   #     if @newsstory.save
    #        redirect_to new_story_path
   # end
    
    def submit
        @news = News.new
    end

    def create
        @news = News.new(news_params)
    
        if @news.save
          redirect_to root_path, notice: 'News succesfully created!'
        else
          render :submit
        end
    end
    
    def home
        @news = News.all
    end
    
    def show
        @news = News.find(news_params)
    end
    
    def comments
    
    end
  
  private
  
  def news_params
   params.require(:news).permit(:title, :source, :author)
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
   
  end
  
  def about
    
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(username: login_params[:username])

    if user && user.authenticate(login_params[:password]) 
      login(@user)
      redirect_to root_path, notice: 'Logged in'
    else
      flash.now[:notice] = 'Invalid username / password combination'
      render :new
    end
  end
  
  def destroy
    logout
    redirect_to root_path, notice: 'Logged out'
  end
  
  private

  def login_params
    params.require(:session).permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
   @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login(@user)
      redirect_to root_path, notice: 'Logged in'
    else
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
  <%= csrf_meta_tags %>
</head>
<body class="container">
  <% if flash[:notice] %>
    <p class="alert alert-info">
      <%= flash[:notice] %>
    </p>
  <% end %>
  
<!-- MAIN NAVIGATION -->
<div class="wrapper">
    <%= render 'shared/layout'%>
</div>
<br><br>

<%= yield %>

<div class="wrapper">
    <%= render 'shared/footer'%>
</div>

</body>
</html>

app/views/news/comments.html.erb
<h1>Pages#comments</h1>
<p>Find me in app/views/pages/comments.html.erb</p>

app/views/news/home.html.erb
<header>
    <%= render @news %>

</header>

app/views/news/submit.html.erb
<h3>Submit a news</h3>
<%= form_for @news do |f| %>
    <%= render "shared/errors", object: @news %>
    <div class="form-group">
        Start typing the news you want to share..
        <%= f.text_field :title, required: true, class: "form-control", placeholder: "title" %>
    </div>
    <div class="form-group">
       <%= f.text_field :source, class: "form-control", placeholder: "source(optional)" %>
    </div>
    <div class="form-group">
        <%= f.button :submit, class: "btn btn-success" %>
    </div>
<% end %>

app/views/news/test.html.erb
<% form_for @news do |n| -%>
    Start typing the news you want to share.. <%= n.text_field :text %>
    <%= n.submit %>
    <% end %>

app/views/pages/about.html.erb
<h3>Group Members</h3>
<p>Marion Padua         April Canete</p>
<p>s3508866             s3564424</p>
<br><br>
<h3>Insert heroku deployed url here</h3>
<h3>insert assignment 2 bibucket url here</h3>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <ul class="errors alert alert-danger">
    <% object.errors.full_messages.each do |msg| %>
      <li> <%= msg %> </li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
<%= link_to "API", "https://github.com/pigfly/RMIT-CSIT-RAD/tree/master/2018_S1/assignment2", target: "_blank", rel: "alternate" %>    
<%= link_to "About", "about"%>    
</div>

app/views/shared/_layout.html.erb
<div class="navbar">
    <div class="img_logo">
        <%= image_tag("logo.png", :style =>'max-width: 150px; max-height: 50px;', :alt => "logo")%>
    </div>
   

    
    <%= link_to "Home", home_path(@news) %>
    <%= link_to "comments", comments_path(@news) %>
    <%= link_to "submit", submit_path(@news) %>

    <% unless logged_in? %>
        <%= link_to "signup", new_user_path %>
        <%= link_to "login", new_session_path %>
    <% end %>

    <% if logged_in? %>
        <%= link_to "logout", sessions_path, method: :delete %>
    <% end %>
</div>
      
      

app/views/shared/_news.html.erb
<div>
    <% link_to news.title, (news.source? ? news.source : news) %>
</div>
<div>
    by <%= news.user.username %>
</div>

app/views/users/new.html.erb
<section class="register-user">
  <header>
    <h1>
      Create a new Account
    </h1>
    
    <div class="row">
      <div class="col-sm-6">
        <%= form_for @user do |f| %>
        <%= render "shared/errors", object: @user %>
        <div class="form-group">
          <%= f.text_field :username, class: "form-control", required: true, placeholder: "username" %>
        </div>
        
        <div class="form-group">
          <%= f.text_field :email, class: "form-control", required: true, placeholder: "email" %>
        </div>

        <div class="form-group">
          <%= f.password_field :password, class: "form-control", required: true, minlength: 10, placeholder: "password" %>
        </div>

        <div class="form-group">
          <%= f.button "Register", class: "btn btn-success" %>
        </div>

        <% end %>
      </div>
    </div>
  </header>
</section>